/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthRequestSchema,
  AuthResponseSchema,
  HTTPValidationError,
} from '../models/index';
import {
    AuthRequestSchemaFromJSON,
    AuthRequestSchemaToJSON,
    AuthResponseSchemaFromJSON,
    AuthResponseSchemaToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface LoginAuthLoginPostRequest {
    authRequestSchema: AuthRequestSchema;
}

export interface RegisterAuthRegisterPostRequest {
    authRequestSchema: AuthRequestSchema;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Login
     */
    async loginAuthLoginPostRaw(requestParameters: LoginAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponseSchema>> {
        if (requestParameters['authRequestSchema'] == null) {
            throw new runtime.RequiredError(
                'authRequestSchema',
                'Required parameter "authRequestSchema" was null or undefined when calling loginAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRequestSchemaToJSON(requestParameters['authRequestSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Login
     */
    async loginAuthLoginPost(requestParameters: LoginAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponseSchema> {
        const response = await this.loginAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register
     */
    async registerAuthRegisterPostRaw(requestParameters: RegisterAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponseSchema>> {
        if (requestParameters['authRequestSchema'] == null) {
            throw new runtime.RequiredError(
                'authRequestSchema',
                'Required parameter "authRequestSchema" was null or undefined when calling registerAuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRequestSchemaToJSON(requestParameters['authRequestSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Register
     */
    async registerAuthRegisterPost(requestParameters: RegisterAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponseSchema> {
        const response = await this.registerAuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
