/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  MeResponseSchema,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MeResponseSchemaFromJSON,
    MeResponseSchemaToJSON,
} from '../models/index';

export interface GetMeMeGetRequest {
    token?: string | null;
}

/**
 * 
 */
export class MeApi extends runtime.BaseAPI {

    /**
     * Get Me
     */
    async getMeMeGetRaw(requestParameters: GetMeMeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeResponseSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Get Me
     */
    async getMeMeGet(requestParameters: GetMeMeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeResponseSchema> {
        const response = await this.getMeMeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
