/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRequestSchema
 */
export interface AuthRequestSchema {
    /**
     * 
     * @type {string}
     * @memberof AuthRequestSchema
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AuthRequestSchema
     */
    password: string;
}

/**
 * Check if a given object implements the AuthRequestSchema interface.
 */
export function instanceOfAuthRequestSchema(value: object): value is AuthRequestSchema {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthRequestSchemaFromJSON(json: any): AuthRequestSchema {
    return AuthRequestSchemaFromJSONTyped(json, false);
}

export function AuthRequestSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRequestSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthRequestSchemaToJSON(value?: AuthRequestSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

