/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResponseSchema
 */
export interface AuthResponseSchema {
    /**
     * 
     * @type {number}
     * @memberof AuthResponseSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AuthResponseSchema
     */
    token: string | null;
}

/**
 * Check if a given object implements the AuthResponseSchema interface.
 */
export function instanceOfAuthResponseSchema(value: object): value is AuthResponseSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthResponseSchemaFromJSON(json: any): AuthResponseSchema {
    return AuthResponseSchemaFromJSONTyped(json, false);
}

export function AuthResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'token': json['token'],
    };
}

export function AuthResponseSchemaToJSON(value?: AuthResponseSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'token': value['token'],
    };
}

