/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeResponseSchema
 */
export interface MeResponseSchema {
    /**
     * 
     * @type {number}
     * @memberof MeResponseSchema
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MeResponseSchema
     */
    email: string;
}

/**
 * Check if a given object implements the MeResponseSchema interface.
 */
export function instanceOfMeResponseSchema(value: object): value is MeResponseSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function MeResponseSchemaFromJSON(json: any): MeResponseSchema {
    return MeResponseSchemaFromJSONTyped(json, false);
}

export function MeResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
    };
}

export function MeResponseSchemaToJSON(value?: MeResponseSchema | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'email': value['email'],
    };
}

